### ISSUE TITLE
Port to ros noetic

### ISSUE THREAD

**Issue by fatmaf** [jackal/jackal_simulator#16]
Hi can the jackal simulator be ported to ros noetic please? 
There are a few other jackal packages that are also not ported to ros noetic. 
Thank you so much

**Comment by civerachb-cpr** [comment]
All Jackal packahges have been released for Noetic already.  In the case of jackal_simulator (and a few others), no changes were necessary from the Melodic branch, so rather than having two identical branches the melodic-devel branch should be used on Noetic.

**Comment by heuristicus** [comment]
This package currently isn't available by running `sudo apt install ros-noetic-jackal-simulator`. Is there some way you could release it to the noetic package server so that it's not necessary to clone the repository?

**Comment by civerachb-cpr** [comment]
Please follow the instructions found at https://packages.clearpathrobotics.com to add Clearpath's package servers to your apt configuration; the packages are released through Clearpath's servers.
