### ISSUE TITLE
Missing simulation features

### ISSUE THREAD

**Issue by mikepurvis** [jackal/jackal_simulator#2]
- [x] IMU: https://github.com/jackal/jackal/issues/10
- [x] GPS: https://github.com/jackal/jackal/issues/11
- [x] Cameras: https://github.com/jackal/jackal/issues/12
- [ ] mast or bridge

**Comment by l0g1x** [comment]
Has this been taken care of yet? I know IMU has been taken care of in pr #13 , but has anybody done the Bumblebee2 implementation? If not i can submit a pull request because i already have it done on my own model

**Comment by mikepurvis** [comment]
Our co-op student made some initial progress simulating the monocular camera, but then got distracted working on getting the real robot's compass working solidly. If you've got bumblebee done, yes, I would definitely like to look!

Note that all of the Jackal packages are overdue for a release. We're hoping to have a reasonably stable set out for the new year.

**Comment by l0g1x** [comment]
I dont believe the package is released as a debian yet, but here is the link to the source: https://github.com/jhu-lcsr/lcsr_camera_models . Im not exactly sure about how you guys would want this implemented; i did see that you guys forked imu_filter_madgwick just for the sake of packaging everything together.. would you want to do the same here?

**Comment by mikepurvis** [comment]
Fantastic— that's terrific to have a package like that. We had been planning on building something similar, but can likely use your work as-is.

We would definitely need debians released; ideally, the repo would be moved to a community ROS org such as ros-simulation or ros-visualization. This way if there was ever a problem with maintenance of the package, it would be possible for one of the org admins to jump in and help out.

**Comment by l0g1x** [comment]
![screen shot 2014-11-30 at 7 58 40 pm](https://cloud.githubusercontent.com/assets/5489842/5240493/ce2d6722-78cb-11e4-9c69-595377560958.png)

Thats how it looks. Publishes left and right camera images and even has launch files incase you wanted to use stereo_image_proc. 

I will try to contact the maintainer again about putting this into a ros package

**Comment by l0g1x** [comment]
Referenced here: https://github.com/jhu-lcsr/lcsr_camera_models/issues/2

**Comment by dniewinski** [comment]
As there is no mast/bridge/arch for a Jackal, and all other additions have been added, this issue will be closed
