### ISSUE TITLE
Binary package missing one dependency

### ISSUE THREAD

**Issue by rgariepy** [jackal/jackal_simulator#3]
Either this package or jackal_desktop needs to install ros-indigo-joint-state-controller

**Comment by shokoofeh** [comment]
This package doesn't have direct dependency  on joint_state_controller. 
It depends on jackal_control which has dependency on joint_state_controller.

**Comment by rgariepy** [comment]
It still should have installed it, right? I followed the wiki instructions (
http://wiki.ros.org/Robots/Jackal/Tutorials/Using%20Jackal%20in%20Simulation)
and came up missing joint_state_controller when I tried to launch it the
first time.

**Comment by mikepurvis** [comment]
Yes it should. This has been fixed in source:

https://github.com/jackal/jackal/blob/indigo-devel/jackal_control/package.xml

We're going to do a round of releases for Jackal shortly, I think.

On Mon, Nov 10, 2014 at 8:21 PM, rgariepy notifications@github.com wrote:

> It still should have installed it, right? I followed the wiki instructions
> (
> 
> http://wiki.ros.org/Robots/Jackal/Tutorials/Using%20Jackal%20in%20Simulation)
> 
> and came up missing joint_state_controller when I tried to launch it the
> first time.
> 
> On Mon, Nov 10, 2014 at 8:04 PM, Shokoofeh Pourmehr <
> notifications@github.com> wrote:
> 
> > This package doesn't have direct dependency on joint_state_controller.
> > It depends on jackal_control which has dependency on
> > joint_state_controller.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jackal/jackal_simulator/issues/3#issuecomment-62485361>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jackal/jackal_simulator/issues/3#issuecomment-62486877
> .

## 

http://uwmike.com
