### ISSUE TITLE
Modify default environment to be more conducive to running mapping

### ISSUE THREAD

**Issue by rgariepy** [jackal/jackal_simulator#4]
The current default environment looks great, but it could use more distinctive &| less symmetrical features to ease SLAM testing/demos. Right now, it's pretty much solely picking up hill contours.

**Comment by mikepurvis** [comment]
Yes, agreed. @Shokoofeh's "Jackal Race" world is much better suited, and has been made the default:

https://github.com/jackal/jackal_simulator/blob/indigo-devel/jackal_gazebo/launch/jackal_world.launch#L6
