### ISSUE TITLE
ResourceNotFound: pointgrey_camera_description

### ISSUE THREAD

**Issue by davetcoleman** [jackal/jackal_simulator#7]
When launching 

```
roslaunch jackal_gazebo jackal_world.launch config:=front_laser
```

Using that package compiled from source, I get the error

```
rospkg.common.ResourceNotFound: pointgrey_camera_description
```

Works fine if I manually install https://github.com/ros-drivers/pointgrey_camera_driver

Thanks!

**Comment by tonybaltovski** [comment]
Should be available soon ros/rosdistro/pull/10009.

**Comment by mikepurvis** [comment]
In shadow already if you're keen: http://www.ros.org/debbuild/indigo.html?q=pointgrey

We'll do some testing and get together a new release of jackal, jackal_simulator, and jackal_desktop, so that they'll all be available in the next sync.

**Comment by davetcoleman** [comment]
thanks, i'll keep this open for others until the next ROS sync

**Comment by dniewinski** [comment]
This doesn't appear to be an issue anymore.  Can it be closed?
