### ISSUE TITLE
No p gain specified for pid

### ISSUE THREAD

**Issue by ghost** [jackal/jackal_simulator#9]
Launching the jackal_world.launch outputs the following error:
```
[ERROR] [1586987092.807651539, 1517.347000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_left_wheel
[ERROR] [1586987092.808212953, 1517.347000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_right_wheel
[ERROR] [1586987092.808681929, 1517.347000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/rear_left_wheel
[ERROR] [1586987092.809196164, 1517.347000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/rear_right_wheel
```
Is there a config file that is missing on the `melodic-devel` branch?

I am using Ubuntu 18.04, ROS Melodic and building jackal packages from source.

**Comment by ghost** [comment]
I used dummy values:
```
/gazebo_ros_control:   
  pid_gains:
    front_left_wheel:
      p: 10.0
      i: 0.01 
      d: 10.0
    front_right_wheel:
      p: 10.0
      i: 0.01 
      d: 10.0
    rear_left_wheel:
      p: 10.0
      i: 0.01 
      d: 10.0
    rear_right_wheel:
      p: 10.0
      i: 0.01 
      d: 10.0
```
I can't move the robot in gazebo after issuing Twist commands on `/cmd_vel` or `/jackal_velocity_controller/cmd_vel` topics.

This could help: https://pasteboard.co/J40MytB.png

**Comment by ashsifat** [comment]
I am having the same issue as well as the error:
Spawn service failed. Exiting.

Could you please let me know if you fixed it? TIA

**Comment by ghost** [comment]
Sorry, I ended up building a non-holonomic mobile robot in Gazebo.
